### ISSUE TITLE
Welcome notebook doesn't open in Apple Safari

### ISSUE THREAD

**Issue by HunterDG** [0xGG/welcome-notebook#2]
Crossnote is great!

[This URL](https://crossnote.app/?repo=https%3A%2F%2Fgithub.com%2F0xGG%2Fwelcome-notebook&branch=master&filePath=README.md) doesn't open the welcome notebook in Apple Safari.  Instead it only opens a new tab with an empty, collapsed "Add a Notebook" dialog.

If I expand the dialog and manually enter the [repo url](https://github.com/0xGG/welcome-notebook), it opens properly.

**Comment by shd101wyy** [comment]
Thank you for posting the issue! Are you using safari on Mac or iPhone or iPad?

**Comment by HunterDG** [comment]
Sorry, was using safari on Mac but seems it affects iOS (iPhone) as well.  Don't have iPad to test.

**Comment by shd101wyy** [comment]
Hi @HunterDG , I would assume the issue is now fixed. Thank you!

**Comment by HunterDG** [comment]
Unfortunately does not appear fixed for me on iOS.  Don’t have laptop nearby to test, will check later.

**Comment by shd101wyy** [comment]
Hi there. Could you try it in incognito window? Cheers 👍

**Comment by HunterDG** [comment]
Hello,
It seems I have the same issue on macOS Safari 13.1.  The behavior I described in the original issue is unchanged, regardless of normal or 'private' window

Happy to help troubleshoot if necessary - assuming you don't have a Mac.

**Comment by HunterDG** [comment]
Seems this is fixed now
